### PR TITLE
Path improvements

### PR DESCRIPTION
**Pull request by tareqhs**
1- Better relativization in newPath, e.g. newPath("../abc")
2- Smarter reuse of ROOT
3- Slight improvement in toString() caching
4- Use standard Arrays.hashCode() in Path.hashCode()

Signed-off-by: Tareq Sharafy <tareq.sha@gmail.com>

### CODE REVIEW

**Comment by skabashnyuk** [comment]
1. You PR should be made according to Eclipse rules. I mean signed.
2. Why so many changes in PathTest? Did you made some changes in spaces?

**Comment by tareqhs** [comment]
hi @skabashnyuk 
1. Done
2. Probably was an issue with my git tool, fixed it.

**Comment by vparfonov** [comment]
ok

**Comment by skabashnyuk** [comment]
ok

**Comment by rainf0x** [comment]
Eclipse CLA confirmed for dror.cohen@sap.com Eclipse CLA confirmed

**Comment by rainf0x** [comment]
Eclipse CLA confirmed for tareq.sha@gmail.com Eclipse CLA confirmed

**Pull request merged**
