### PR TITLE
checkout API fix conflict exception - change GitException to APIexception

### PR DESCRIPTION
**Pull request by i053322**
checkout API change GitException to APIexception

Change-Id: I7bd58baa5d0e015107343f8ed1610ffea43b0a0b

Signed-off-by: i053322 yossi.balan@sap.com

### CODE REVIEW

**Comment by tareksha** [comment]
why?

**Comment by offer8** [comment]
The GitException type does not expose the right checkout conflict exception in the inheritance tree which we need to the full checkout scenario.

**Comment by offer8** [comment]
Can someone please merge this one?

**Comment by skabashnyuk** [comment]
Not yet. Can you explain more why you need that

**Comment by i053322** [comment]
In checkout scenario when you move between branches you could get conflict error.
It could occurred:
1. if you did any change and then you to move to different branch that based on different remote.
   1. if you did any commit and you tried to move to different branch on the same remote 

In this case the error from the jcheckoutCommand.call() is CheckoutConflictException and not GitAPIException.

**Comment by vinokurig** [comment]
Can you additionally catch CheckoutConflictException and handle it?

**Comment by i053322** [comment]
This is what I did in my change I added another catch for the CheckoutConflictException

**Comment by vinokurig** [comment]
Where? As I see you just changed throwing GitException to ApiException. As I understood, you want to handle CheckoutConflictException, but native git does not produce such exception. May be you should handle it in JgitConnection?

**Comment by i053322** [comment]
I added the implementation for the catch  in the jgitConnection

**Comment by vinokurig** [comment]
I can not see any changes in JgitConnection in this Pull request, I only see changes in NativeGitConnection

**Comment by offer8** [comment]
Hi,

As first phase we change the che-api layer to support the new exception type.
Second phase, after the merge of JGit branch to 3.x is completed we will push the new logic which we inserted in the JGitConnection checkout method.

The reason for the change in the exception type is that we need to throw ConflictException which being extended from ApiException.
We do this in order to return the right HTTP status and message for the client.
This logic is placed in ApiExceptionMapper.java class that builds the relevant HTTP response according to the exception type.
GitException is not in the inheritance tree of APIException.

Regards,
Offer.

**Comment by sleshchenko** [comment]
I agree that it would be better to throw exception with right response code. But I think that replacing GitException with ApiException is a wrong way to implement it. 
I think it would be better to remove GitException at all (or mark deprecated for now) and add to throws section specific child classes of ApiException to wit ServerException, ConflictException, NotFoundException etc. And add to java doc  of GitConnection information about required behaivour for implementation (which exception should be thrown in which cases). We do the same for our Daos interfaces for example [WorkspaceDao](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/WorkspaceDao.java#L58-66)

@skabashnyuk WDYT?

**Comment by i053322** [comment]
i think you right and you proposal should be the way to raise error message in git.
For example in the checkout Jgit throw the following errors :
GitAPIException, RefAlreadyExistsException, RefNotFoundException, InvalidRefNameException, CheckoutConflictException
so in the JGitConnection in the checkout I need to create new Exception for each type meaning 
GitAPIException - throw ApiException 
RefAlreadyExistsException - need to create new message
RefNotFoundException,  - throw NotFoundException
InvalidRefNameException,  - need to create new message
CheckoutConflictException - throw ConflictException

This mean that I need also to add new check for the logic in the ApiExceptionMapper for the new message ( RefAlreadyExistsException , InvalidRefNameException )
Is it ok ?
Also what do you think I need to do in the native can I throw ApiExcption for all the messages ?
Can we start to do the change only for the checkout API and continue later for the other apis ?

Regards,
Yossi

**Comment by gazarenkov** [comment]
I think the best way to apply everywhere is to:
- have fine grained logical exception on business logic
- add a mapping for these exceptions - to - REST friendly (ApiException) in a specific module 

so if I understand you well, I am +1 for this

**Comment by i053322** [comment]
what do I need to do in the case of the native ? can I throw  ApiExcption ?

**Pull request closed without merging**
