### PR TITLE
Support DTOs with properties typed 'any'

### PR DESCRIPTION
**Pull request by tareqhs**
1- Serialzie and de-serialize JsonElement properties as raw JSONs
2- Deep-copy them in the generated copy constructors
3- Avoid redundant copying in fromJsonString() and toJson() cases

Signed-off-by: Tareq Sharafy <tareq.sharafy@sap.com>

### CODE REVIEW

**Comment by vparfonov** [comment]
can you provide the same for functionality for client side DTO templates (DtoImplClientTemplat.java)

**Comment by tareqhs** [comment]
Hi @vparfonov,
Sorry for delay.
I noticed that the tests do not generate client implementations for the DTOs. I looked into that and noticed that the client generates GWT JSON code, which means JsonElement is not suitable as a cross-environment type. I suggest using Object instead, which evaluate to JSONValue in client and JsonElement in server. Sounds fine?

**Comment by vparfonov** [comment]
Hi @tareqhs looks good i just have two question:
1. Did you make some test with client-side DTO generation?
2. What means "Int" in fromJsonObjectInt(boolean)?

**Comment by tareqhs** [comment]
Hi @vparfonov,
Thanks for the review.
1. The current code has no tests for client code at all, but i did add the client-side generation with relevant dependencies to make everything compiles (which wasn't done before). I would be glad if we lay out tests for all client code.
2. Int just stands for 'Internal', added this to avoid generated overloaded functions because this is problematic in client code (e.g. JS).

**Pull request merged**
