### PR TITLE
Add ability to configure selection with opened file in editor

### PR DESCRIPTION
**Pull request by vzhukovskii**
Editor now has ability to provide into selection model current opened file. And Current class fqn provider now listen selection changed events to have ability provide fqn on selected file in Project Explorer or another place.

Screencast: https://slack-files.com/T02G3VAG4-F0JF7CB0T-650823b3be

Related PR: https://github.com/codenvy/che-plugins/pull/549

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
:+1: really usefull

**Comment by TylerJewell** [comment]
Does "fqn" mean "fully qualified name"?

**Comment by azatsarynnyy** [comment]
yes

**Comment by vparfonov** [comment]
ok

**Pull request merged**
