### PR TITLE
Bug fix: populate workspace and project fields of BuildTaskDescriptor

### PR DESCRIPTION
**Pull request by tareqhs**
Change-Id: Icf9cf5db9b6cdc768a55c7fd31e123458833a6a7
Signed-off-by: Tareq Sharafy <tareq.sharafy@sap.com>

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Could you plz inline methid withCommonDescriptorProperties

**Comment by tareqhs** [comment]
hi @skabashnyuk,
wouldn't inlining it make the operation less maintainable?

**Comment by skabashnyuk** [comment]
Author of BuildQueueTask and I think that it's better to have it a bit less maintainable, than one small private method ))

**Comment by benoitf** [comment]
I think Tareq proposal is more maintainable as well. If new methods are added, all attributes will be correctly setup by calling this single method

**Pull request merged**
