### PR TITLE
Proposal to add recent files functionality

### PR DESCRIPTION
**Pull request by vzhukovskii**
New dialog will display list of recently opened files (file name and path).
Double clicking on file will open editor.

User may call this dialog by hotkey Ctrl+E (Linux/Windows) or Command+E (Mac)

Also new menu item: File->Recent.
Will contains the same list. Also user can clear recent list by menu item File->Recent->Clear Recent List

Screencast: https://slack-files.com/T02G3VAG4-F0H2V70HX-a2d294fdf9
@vparfonov @skabashnyuk @evidolob wdyt?

### CODE REVIEW

**Comment by TylerJewell** [comment]
Can you place this into new Edit main menu?  This issue is being worked on now.  See new menu spec on the wiki

**Comment by vzhukovskii** [comment]
No problem.

**Comment by vzhukovskii** [comment]
Done

**Comment by TylerJewell** [comment]
Is there a key binding that will open this dialog?  If not can you propose a CTRL binding?

**Comment by vzhukovskii** [comment]
There is a key binding for this dialog: Ctrl+E (Linux/Windows) or Command+E (Mac)

**Comment by TylerJewell** [comment]
Thanks.  Looks good

**Comment by vparfonov** [comment]
ok

**Pull request merged**
