### PR TITLE
Add "." to validity of project name .

### PR DESCRIPTION
**Pull request by i048695**
Dot (".") can be added to new project name.  

Change-Id: Ib79d741e70ac561b9bac4470661fe4f178195fb5
Signed-off-by: i048695 lev.zak@sap.com

### CODE REVIEW

**Comment by skabashnyuk** [comment]
PR is not clear. Can you elaborate a bit more about your changes? what is it and why do we need it?

**Comment by i048695** [comment]
Hi
My name Lev Zak
I am from develop team of DEVX SAP.
I have task to enable create new project with dot(".") in name . I add some change to ProjectService.java   (if (!Pattern.compile("[a-zA-Z0-9]+[\\.\\w-]*").matcher(name).matches()) {  )

**Comment by i048695** [comment]
Hi
We need to create project with dot in name . We can't replace dot "." to something else . This is the reason that i add this change .

**Comment by skabashnyuk** [comment]
Examples?
dots can be at beginning or end of the name?

**Comment by i048695** [comment]
For example 
aaa.bbb

**Comment by tareksha** [comment]
Hi @skabashnyuk 
as Lev explained, the goal is to support project names that contain dots - much like java packages. 
do you approve the change?

**Comment by skabashnyuk** [comment]
Yes.  In genera @tareqhs  we are good to go.
BTW are you able to add some tests?

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
