### PR TITLE
IDEX-4090: Remove NewUser DTO and refactor UserService

### PR DESCRIPTION
**Pull request by akorneta**
@skabashnyuk @evoevodin

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok. @evoevodin ?

**Comment by skabashnyuk** [comment]
ok if @benoitf  and @evoevodin ok.

**Comment by evoevodin** [comment]
Add test which checks the situation when admin creates a new user with email and without it.

**Comment by benoitf** [comment]
+1 (ok for UD usecase)

**Comment by evoevodin** [comment]
ok

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
