### PR TITLE
General injection-based filtering of system files in VFS

### PR DESCRIPTION
**Pull request by tareqhs**
Currently, system-level filtering of virtual files is done through hard-coded checks in VFS projects. This is bad because the actual source of truth for such checks is in layers that are higher than VFS, e.g. hiding misc.xml from che-core-api-project.

A better solution is to allow defining decoupled injection-based filters that allow filtering VFS paths from their correct sources of truth in components at higher layers.

Signed-off-by: Tareq Sharafy <tareq.sha@gmail.com>

### CODE REVIEW

**Comment by vparfonov** [comment]
ok

**Comment by tareqhs** [comment]
hi @vparfonov ,
thank you. can this be merged?

**Comment by skabashnyuk** [comment]
ok

**Comment by rainf0x** [comment]
Eclipse CLA confirmed for tareq.sha@gmail.com Eclipse CLA confirmed

**Pull request merged**
