### PR TITLE
Implemented new search logic with support for maxItems and skipCount

### PR DESCRIPTION
**Pull request by Ori-Libhaber**
1. Added support for maxItems and skipCount query parameters, as described in email thread:
    [che-dev] Search API
2. Search result is now encapsulated in SearchResult object which provides additional metadata on search.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
PR is not signed according to Eclipse rules. Please do that.

**Comment by Ori-Libhaber** [comment]
Do you mean eclipse CLA?

**Comment by Ori-Libhaber** [comment]
I have signed the Eclipse CLA.

**Comment by skabashnyuk** [comment]
I mean you git commit.

**Pull request closed without merging**
