### PR TITLE
Remove gwt compiling for IE9

### PR DESCRIPTION
**Pull request by sleshchenko**
@vparfonov @evidolob @azatsarynnyy I removed settings for ie9. 
And I have question: Will it work https://github.com/codenvy/che-core/blob/784fed052d53ea3d98c1232936afeb68a2d0e90b/commons/che-core-commons-gwt/src/main/resources/org/eclipse/che/ide/Commons.gwt.xml#L46-L54 if we don't set user agent to android and iphone?

### CODE REVIEW

**Comment by vparfonov** [comment]
Ok for merging 
Sorry, but I don't know

**Comment by evidolob** [comment]
What do you mean: "Will it work" ?

**Comment by sleshchenko** [comment]
I mean "Will it compiled for android and for iphone?"

**Comment by evidolob** [comment]
No it mean that if user agent is iphone use IPhoneImpl, not a compile new permutation

**Comment by sleshchenko** [comment]
So We can just remove it?

**Comment by evidolob** [comment]
if we not interesting in detecting iphone, yes

**Comment by sleshchenko** [comment]
iphone can be detected even if we do not add user.agent="iphone" https://github.com/codenvy/che-core/pull/476/files#diff-4f669b01dc4a4299e39b83ef32a6380dR22?

**Comment by evidolob** [comment]
they use 'mobile.user.agent' not a 'user.agent', so if you test it, I think you can delete them

**Comment by sleshchenko** [comment]
you're right. I'll investigate this.

**Pull request merged**
