### PR TITLE
IDEX-3876: Change the titles and messages of all Che notifications

### PR DESCRIPTION
**Pull request by vzhukovskii**
@vparfonov @ashumilova

### CODE REVIEW

**Comment by vparfonov** [comment]
maybe better solution add message on client side, it allow  make localization

**Comment by vzhukovskii** [comment]
Its a good remark, but it may estimation for this task is undefined. I think we should do this pluing by plugin in future.

**Comment by skabashnyuk** [comment]
-1 to changing message in vfs. This work will need to be done again after we update our vfs implementation.

**Comment by ashumilova** [comment]
+1

**Comment by vparfonov** [comment]
ok

**Pull request merged**
