### PR TITLE
Disabled tests due to failure ones

### PR DESCRIPTION
**Pull request by vzhukovskii**
Temporary disabled due to failure ones.
I'm blocked to build che-core with tests.

Debug information for you:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: TestNG652Configurator
2015-12-16 17:21:22,936[main]             [INFO ] [org.eclipse.jetty.util.log 186]      - Logging initialized @390ms
2015-12-16 17:21:22,983[main]             [INFO ] [o.eclipse.jetty.server.Server 345]   - jetty-9.3.1.v20150714
2015-12-16 17:21:23,053[main]             [INFO ] [o.e.j.s.handler.ContextHandler 737]  - Started o.e.j.s.ServletContextHandler@48f2bd5b{/,null,AVAILABLE}
2015-12-16 17:21:23,059[main]             [INFO ] [o.e.j.server.ServerConnector 270]    - Started ServerConnector@74235045{HTTP/1.1,[http/1.1]}{0.0.0.0:10446}
2015-12-16 17:21:23,060[main]             [INFO ] [o.eclipse.jetty.server.Server 397]   - Started @516ms
2015-12-16 17:21:23,384[main]             [INFO ] [o.e.c.a.m.s.MachineManager 164]      - Creating machine [ws = wsId: env = env1: machine = MachineName]
2015-12-16 17:21:23,462[main]             [INFO ] [o.e.c.a.m.s.MachineManager 166]      - Machine [ws = wsId: env = env1: machine = MachineName] was successfully created, its id is 'machinez08tg92osb2hx2wb'
2015-12-16 17:21:23,465[main]             [INFO ] [o.e.c.a.m.s.MachineManager 164]      - Creating machine [ws = wsId: env = env1: machine = @name!]
{"tags":[],"creator":"user123","name":"name","permissions":{"groups":[{"acl":["read","search"],"name":"public"}],"users":{}},"id":"recipe01t4n45d2718zwsa","type":"docker","script":"FROM ubuntu\n","links":[{"rel":"get recipe script","href":"/recipe/recipe01t4n45d2718zwsa/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/recipe01t4n45d2718zwsa","method":"DELETE","parameters":[]}]}
[{"tags":[],"creator":"user123","id":"id1","type":"docker","script":"script1 content","links":[{"rel":"get recipe script","href":"/recipe/id1/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/id1","method":"DELETE","parameters":[]}]},{"tags":[],"creator":"user123","id":"id2","type":"docker","script":"script2 content","links":[{"rel":"get recipe script","href":"/recipe/id2/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/id2","method":"DELETE","parameters":[]}]}]
{"tags":["java","mognodb"],"creator":"someone2","name":"name","permissions":{"groups":[],"users":{"user123":["read","write"]}},"id":"recipe123","type":"docker","script":"FROM ubuntu\n","links":[{"rel":"get recipe script","href":"/recipe/recipe123/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/recipe123","method":"DELETE","parameters":[]}]}
FROM ubuntu

[{"tags":["java"],"creator":"user123","id":"id1","type":"docker","script":"script1 content","links":[{"rel":"get recipe script","href":"/recipe/id1/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/id1","method":"DELETE","parameters":[]}]},{"tags":["java","mongodb"],"creator":"user123","id":"id2","type":"docker","script":"script2 content","links":[{"rel":"get recipe script","href":"/recipe/id2/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/id2","method":"DELETE","parameters":[]}]}]
{"tags":["java","mongo"],"creator":"user123","name":"name","permissions":{"groups":[{"acl":["read"],"name":"public"}],"users":{}},"id":"recipecex4e8gjxfa99h6k","type":"docker","script":"FROM ubuntu\n","links":[{"rel":"get recipe script","href":"/recipe/recipecex4e8gjxfa99h6k/script","produces":"text/plain","method":"GET","parameters":[]},{"rel":"remove recipe","href":"/recipe/recipecex4e8gjxfa99h6k","method":"DELETE","parameters":[]}]}
{"message":"User user123 doesn't have access to use 'public: search' permission"}
{"message":"User user123 doesn't have access to recipe id"}
{"message":"Recipe script required"}
{"message":"Recipe type required"}
{"message":"Recipe required"}
{"message":"Recipe name required"}
{"message":"User user123 doesn't have access to update recipe id"}
{"message":"User user123 doesn't have access to update recipe id permissions"}
{"message":"User user123 doesn't have access to recipe recipe123"}
{"message":"User user123 doesn't have access to recipe recipe123"}
2015-12-16 17:21:24,601[main]             [WARN ] [o.e.j.s.handler.ContextHandler 1308] - o.e.j.s.h.ContextHandler@69cac930{/,null,null} contextPath ends with /
2015-12-16 17:21:24,603[pool-3-thread-1]  [INFO ] [o.eclipse.jetty.server.Server 345]   - jetty-9.3.1.v20150714
2015-12-16 17:21:24,605[pool-3-thread-1]  [INFO ] [o.e.j.s.handler.ContextHandler 737]  - Started o.e.j.s.h.ContextHandler@69cac930{/che/api/ext/api/workspace123/java,null,AVAILABLE}
2015-12-16 17:21:24,605[pool-3-thread-1]  [INFO ] [o.e.j.server.ServerConnector 270]    - Started ServerConnector@7d11f461{HTTP/1.1,[http/1.1]}{0.0.0.0:52561}
2015-12-16 17:21:24,606[pool-3-thread-1]  [INFO ] [o.eclipse.jetty.server.Server 397]   - Started @2062ms
2015-12-16 17:21:25,110[main]             [WARN ] [o.eclipse.jetty.server.Server 692]   - 
2015-12-16 17:21:25,130[main]             [INFO ] [o.e.j.server.ServerConnector 310]    - Stopped ServerConnector@74235045{HTTP/1.1,[http/1.1]}{0.0.0.0:10446}
2015-12-16 17:21:25,136[main]             [INFO ] [o.e.j.s.handler.ContextHandler 847]  - Stopped o.e.j.s.ServletContextHandler@48f2bd5b{/,null,UNAVAILABLE}
Tests run: 64, Failures: 1, Errors: 0, Skipped: 31, Time elapsed: 2.595 sec <<< FAILURE! - in TestSuite
setUpClass(org.eclipse.che.api.machine.server.proxy.MachineExtensionProxyServletTest)  Time elapsed: 0.516 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.eclipse.che.api.machine.server.proxy.MachineExtensionProxyServletTest.setUpClass(MachineExtensionProxyServletTest.java:131)


Results :

Failed tests: 
  MachineExtensionProxyServletTest.setUpClass:131 NullPointer

Tests run: 46, Failures: 1, Errors: 0, Skipped: 13

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.207 s
[INFO] Finished at: 2015-12-16T17:21:25+02:00
[INFO] Final Memory: 41M/950M
[INFO] ------------------------------------------------------------------------

```
Mechanism of creating server should be refactored.

@skabashnyuk @vparfonov @garagatyi

### CODE REVIEW

**Comment by vzhukovskii** [comment]
System Info:
```$ cat /etc/os-release 
NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"```

Docker version 1.8.2, build 0a8c2e3

```mvn -version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T22:10:27+02:00)
Maven home: /opt/apache-maven-3.3.1
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib64/jdk1.8.0_45/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "3.16.6-2-desktop", arch: "amd64", family: "unix"```

**Comment by garagatyi** [comment]
Did you debug tests to find the reason of failure?

**Comment by vzhukovskii** [comment]
Reason is somewhere inside embbed jetty server. I didn't have much time to debug it because I have another issue to do in this sprint.

**Comment by vparfonov** [comment]
Did we have issue on this problem?

**Comment by skabashnyuk** [comment]
Closed as not constructive discussion.

**Pull request closed without merging**
