### PR TITLE
IDEX-3431: Add close file hot key

### PR DESCRIPTION
**Pull request by vzhukovskii**
New hotkey binded to:
Win/Linux: Alt+w
Mac: Ctrl+w

@vparfonov

### CODE REVIEW

**Comment by skabashnyuk** [comment]
you mean ⌘ + W for mac ?

**Comment by vzhukovskii** [comment]
Not command. Control button.

**Comment by vzhukovskii** [comment]
⌘ + W wil close chrome tab on mac

**Comment by skabashnyuk** [comment]
ok

**Comment by vparfonov** [comment]
ok

**Pull request merged**
