### PR TITLE
IDEX-2389: Add getProjectExplorerSelection method in SelectionAgent

### PR DESCRIPTION
**Pull request by vinokurig**
When performing git commit with "add selected files" check-box selected and console part is active, NPE appears because the getSelection method in Selection agent returned a selection of console part, but we need a selection of project explorer
@vparfonov @skabashnyuk  please review

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok for me. @vparfonov ?

**Comment by azatsarynnyy** [comment]
I'm disagree with this solution. It breaks concept of the **Selection agent**.
Each part has it's own object that **Selection agent** interacts with, some kind of part's context. Part can set any object into selection. **Selection agent** provides an access to the selection of the active part. 
This solution does not fit into this concept of the **Selection agent**.

Why don't you use ```projectExplorer.getSelection()``` if you need selection of the Project Explorer?

@vparfonov WDYT?

**Comment by vinokurig** [comment]
I can, but I think old get selection method In Selection agent can be confusing as it can return anything. I added this method to split Selection agent, so no we can receive a selection from active part and a selection from project explorer instead of injecting ProjectExplorer just to get a selection from it.

**Comment by azatsarynnyy** [comment]
This is the main idea of the **Selection Agent** - provide a way of getting current app-wide selection. It may be anything

**Comment by vparfonov** [comment]
agree with @azatsarynnyy this not good decisions add getProjectExplorerSelection

**Pull request closed without merging**
