### PR TITLE
IDEX-3191 CodenvyBootstrap --> CheBootstrap

### PR DESCRIPTION
**Pull request by benoitf**
Flag CodenvyBoostrap as @deprecated
Introduce CheBoostrap (reading from WEB-INF/classes/che)

### CODE REVIEW

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
LGTM

**Comment by skabashnyuk** [comment]
@benoitf  Don't forget to merge it in 4.0

**Comment by benoitf** [comment]
also backported in 4.0

**Pull request merged**
