### PR TITLE
Rename mixinTypes field to mixins

### PR DESCRIPTION
**Pull request by sleshchenko**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
LGTM

**Comment by vparfonov** [comment]
ok

**Comment by tareqhs** [comment]
Hi,
I've already made this change
https://github.com/codenvy/che-core/commit/00aedf6b7a917c89fb4b8f73cb70425a8dc2bb85

**Comment by sleshchenko** [comment]
You are right. But there are some code with mixinTypes in 4.0 branch https://github.com/codenvy/che-core/blame/4.0/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/projecttype/wizard/presenter/ProjectWizardPresenter.java#L154 after merging pull #414 https://github.com/codenvy/che-core/pull/414/files#diff-936822732ef5c8e95d5137122dcca59bL160

**Pull request merged**
