### PR TITLE
Support both http and https in git server read-only URL

### PR DESCRIPTION
**Pull request by tal-sapan**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Thanks for contribution.
Please sign commit according to eclipse rules

**Comment by tal-sapan** [comment]
Hi,
Could you check if it is signed correctly now?

**Comment by skabashnyuk** [comment]
No
Please read 
https://github.com/codenvy/che/blob/master/CONTRIBUTING.md
https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Foundation_Contributor_License_Agreement

**Comment by tal-sapan** [comment]
Thanks. I signed the Eclipse CLA but I can't update this pull request because there are no differences in the commit. Should I close this one and create a new pull request?

**Comment by benoitf** [comment]
you can update your branch by rewriting history of it
git commit --amend
and then push force your branch. This will update the PR

**Comment by skabashnyuk** [comment]
@tal-sapan  your Eclipse CLA is not confirmed for tal.sapan@sap.com

**Comment by benoitf** [comment]
Eclipse CLA
it seems it is confirmed

**Comment by skabashnyuk** [comment]
Yes. Sorry. Probably some caching issue
Eclipse CLA confirmed for tal.sapan@sap.com Eclipse CLA confirmed

**Comment by skabashnyuk** [comment]
ok for me

**Comment by tal-sapan** [comment]
Hi,
I would appreciate, if possible, that this PR would be merged before switching the master branch to 4.0 so it doesn't have to be rebased against the new branch.
Thanks.

**Pull request merged**
