### PR TITLE
Add support for checkout exception

### PR DESCRIPTION
**Pull request by i053322**
add a mapper for checkout git exceptions
add new messages : GitConlict , GitInvalidRefName , GitRefAlreadyExist , GitRefNotFound

Change-Id: I9f8270c194958f69a59ebc6ab25791c83bdd8e61
Signed-off-by: i053322 yossi.balan@sap.com

### CODE REVIEW

**Comment by i053322** [comment]
@offer8

**Comment by offer8** [comment]
@vinokurig

**Comment by vinokurig** [comment]
Please create this pull request in https://github.com/eclipse/che
Changes will be here after they will be merged in eclipse CHE

**Comment by i053322** [comment]
@vinokurig - Do you add the change also to 3.x ?

**Comment by vinokurig** [comment]
@i053322 I will add the change to 3.x after it will be approved in 4.x

**Comment by skabashnyuk** [comment]
@vinokurig  can you add link to 4.x PR?

**Comment by vinokurig** [comment]
https://github.com/eclipse/che/pull/1726

**Pull request closed without merging**
