### PR TITLE
IDEX-3406: Use environment name in WorkspaceHooks#beforeStart method

### PR DESCRIPTION
**Pull request by evoevodin**
We need to know environment name which is used for start as well as account id to analyze resources and related stuff.

### CODE REVIEW

**Comment by evoevodin** [comment]
@skabashnyuk, @garagatyi review please

**Comment by skabashnyuk** [comment]
LGTM

**Comment by garagatyi** [comment]
LGTM

**Comment by garagatyi** [comment]
LGTM

**Pull request merged**
