### PR TITLE
IDEX-2989, IDEX-3010: Wrong behaviours with render package nodes and …

### PR DESCRIPTION
**Pull request by vzhukovskii**
…fix related with open file action
@vparfonov

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok. what about @vparfonov ?

**Comment by vparfonov** [comment]
ok, what about tests?

**Comment by vzhukovskii** [comment]
they will be in separate commit

**Comment by vzhukovskii** [comment]
merged with squash https://github.com/codenvy/che-core/commit/e35e022aa869927defb6711fae0228a204818d93

**Pull request closed without merging**
