### PR TITLE
[#206 - issue] Private constructors changed in ParameterizedTypeImpl.java

### PR DESCRIPTION
**Pull request by alexVengrovsk**
According to issue #206, we can remove code overhead by making these changes.

But, it is still a question - Will this class provide the ```ownerType``` variable's instantiation through static generation methods. If so, than all these changes are inappropriate, and the different approach should be used (there should be static generation methods with three parameters):
```
public static ParameterizedType newParameterizedType(Type ownerType, 
   Class<?> rawType, Type typeArgument) {
   return new ParameterizedTypeImpl(ownerType, rawType, typeArgument);
} 
```
and
```
public static ParameterizedType newParameterizedType(Type ownerType, 
   Class<?> rawType, Type... typeArgument) {
   return new ParameterizedTypeImpl(ownerType, rawType, typeArgument);
} 
```
And class will need its ```private final Type ownerType``` variable back, and two constructors(everyone with three parameters)

### CODE REVIEW

**Comment by benoitf** [comment]
I would say that one constructor should still call the other one

**Comment by benoitf** [comment]
with varags, there could have only one constructor
ParameterizedTypeImpl(Class<?> rawType, Type... types)

as well

    public static ParameterizedType newParameterizedType(Class<?> rawType, Type... typeArguments)
is redundant with
    public static ParameterizedType newParameterizedType(Class<?> rawType, Type typeArgument)

as for the method we can give only one argument if we want

**Comment by alexVengrovsk** [comment]
You are right. I can change it to one constructor only.

**Comment by benoitf** [comment]
Now I'm thinking that we may also think why we need to use a static method while we could use directly the constructor

**Comment by alexVengrovsk** [comment]
Yes, it is a question to think about. I dont see any help from static methods. We don't create a singleton here.
Instances of this class were created only twice in DtoFactory. java. We can easily replace static methods and use just constructors.

**Comment by benoitf** [comment]
@skabashnyuk WDYT ?

**Comment by alexVengrovsk** [comment]
Please, check my new commit

**Comment by benoitf** [comment]
looks like a lot simpler for me

**Comment by skabashnyuk** [comment]
Alex did you test che  assembly with this changes?

**Comment by alexVengrovsk** [comment]
No. I didn't perform any additional testing

**Comment by benoitf** [comment]
@skabashnyuk I've rebuild che assembly with Alex changes and it's OK on my side

**Comment by alexVengrovsk** [comment]
@benoitf, thank you for testing my changes!

**Pull request merged**
