### PR TITLE
Reuse code in DefaultProjectManager

### PR DESCRIPTION
**Pull request by tareqhs**
Some (most) logic of creating projects and adding modules to new folders is similar. I extracted the common logic into a single function to avoid double maintenance. A smaller part of this logic is also shared with converting a folder to a project.

Signed-off-by: Tareq Sharafy <tareq.sha@gmail.com>

### CODE REVIEW

**Comment by skabashnyuk** [comment]
1. You PR should be made according to Eclipse rules. I mean signed.
2. Can you elaborate more. What this change is doing?

**Comment by tareqhs** [comment]
hi @skabashnyuk 
1. Done
2. Commit message & PR description updated

**Comment by vparfonov** [comment]
ok

**Comment by skabashnyuk** [comment]
ok

**Comment by rainf0x** [comment]
Eclipse CLA confirmed for tareq.sha@gmail.com Eclipse CLA confirmed

**Pull request merged**
