### PR TITLE
Use HttpJsonRequest instead of HttpJsonHelper (3.x)

### PR DESCRIPTION
**Pull request by tareksha**
Signed-off-by: Tareq Sharafy tareq.sha@gmail.com

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok. @tareqhs  you can merge this pr

**Comment by tareksha** [comment]
@skabashnyuk currently I'm running several integration tests to make sure everything is consistent. is there a way to run the travis ci that used to validate 3.x when it was master ?

**Comment by skabashnyuk** [comment]
@tareqhs  Since che is >3 repositories(che-core che-plugins, che3) I don't know how to do that correctly.
May be you    can trigger individual repositories.

**Comment by tareksha** [comment]
all fine

**Pull request merged**
