### PR TITLE
Install maven 3.x before ci starts

### PR DESCRIPTION
**Pull request by tareksha**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok. Squash commits before merge please.

**Comment by tareksha** [comment]
@skabashnyuk  had to disable . travis provides maven 3.2 and Che requires 3.3, which is failing to install and run correctly in travis . will enable once fixed, meanwhile tests should run locally

**Comment by skabashnyuk** [comment]
@tareqhs  What we can do?

**Comment by tareksha** [comment]
@skabashnyuk we'll have to investigate into this separately without affecting 3.x i guess, otherwise we will get constant false negatives in all pull requests. if you have any immediate solutions this can be very useful.

**Pull request merged**
