### PR TITLE
Make all DTO-related projects modules of same sub-parent

### PR DESCRIPTION
**Pull request by tareqhs**
This allow for a better lifecycle management of all DTO stuff and paves the way for conveniently adding more tools that aid the DTO framework later on.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Not clear for me what issue you are trying to solve. Can you clarify?

**Comment by tareqhs** [comment]
Hi @skabashnyuk ,
First, right now the source of DTO is not grouped into a single hierarchy which makes it less convenient to develop and build it like other parts of Che code. Second, I'm planning to propose alternative tooling for DTO generation based on standard annotation processing instead of the current set of method, this might end up having three non-grouped DTO projects.

**Comment by benoitf** [comment]
hi, about the new tooling, it will be proposed as a replacement of the current maven plugin ?

**Comment by tareqhs** [comment]
hi @benoitf ,
the new tooling is a separate issue, but yes - i'll suggest gradually replacing the current method with a standard annotation processing one. another important thing i will introduce i using text templates instead of the unmanageable 'string append' hundreds of times all over the generator source code. I'll keep you posted about this.

**Comment by benoitf** [comment]
ok, so +1 for me grouping all the dto modules into a dedicated maven module

**Comment by skabashnyuk** [comment]
@tareqhs I don't see a big profit of grouping two artifacts in some folder. Yes it can looks simple but didn't bring some huge profit. Is there any technical reason to do so?

**Comment by tareqhs** [comment]
hi @skabashnyuk ,
the benefits we explained in the previous comment. gently asking, is "huge profit" a required criteria for patching Che? what about general clean-ups, refactoring, minor code alignments, ...

**Comment by skabashnyuk** [comment]
I would like to avoid any artifact movement before you propose something concrete with new DTO generators.
BTW Since we have more then one maven plugin I'm start thinking about separate repository for maven staff. I think if you proposal with new DTO generator will become popular special "maven" git repository would be logical for this kind of staff.

**Pull request closed without merging**
