### PR TITLE
IDEX-4053: Add attributes <String, String> field to CommandDTO and re…

### PR DESCRIPTION
**Pull request by vzhukovskii**
…move previewURL field from it

@vparfonov @gazarenkov @skabashnyuk @ashumilova pls, review

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok @vparfonov ?

**Comment by garagatyi** [comment]
equals, hashcode and toString are broken. Use getter for attributes. It will work in a different way before/after lazy initialization

**Comment by vzhukovskii** [comment]
@garagatyi done

**Comment by vparfonov** [comment]
ok

**Pull request merged**
